FROM node:22

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY package*.json pnpm-lock.yaml ./
COPY prisma ./prisma/

RUN npm install -g pnpm
RUN pnpm install
RUN npx prisma generate

COPY . .

EXPOSE 9000
CMD ["pnpm", "dev"]
